workflows:
  android-workflow-dev:
    name: Android workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    environment:
      flutter: 3.29.0
      groups:
        - firebase
    triggering:
      events:
        - push
        - pull_request
      branch_patterns: # Include or exclude watched branches
        - pattern: feature/codemagic
          include: true
          source: true
    artifacts:
      - build/**/outputs/bundle/developmentRelease/**/*.aab
      - build/**/outputs/apk/development/**/*.apk
      - build/**/outputs/apk/production/**/*.apk
    scripts:
      - name: Pub get
        script: flutter pub get
      - name: Build apk
        script: flutter build apk --release --build-name=1.0.2 --build-number=6 --flavor development --dart-define=BASE_URL=https://api.unsplash.com/
      - name: Get last version
        script: |
          LATEST_BUILD_VERSION=$(firebase-app-distribution get-latest-build-version -p 220062871728 -a 1:220062871728:android:17d8024f4a5fc9e32b8b75)
          echo "$LATEST_BUILD_VERSION"
      - name: Build aab
        script: flutter build aab --release --flavor development
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: 1:220062871728:android:17d8024f4a5fc9e32b8b75
          groups:
            - phongpvs-team
          artifact_type: 'apk'


  android-workflow-production:
    name: Android workflow production
    max_build_duration: 120
    instance_type: mac_mini_m2
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    environment:
      flutter: 3.29.0
    triggering:
      events:
        - pull_request
      branch_patterns: # Include or exclude watched branches
        - pattern: main
          include: true
          source: false
    artifacts:
      - build/**/outputs/bundle/productionRelease/**/*.aab
    scripts:
      - name: Pub get
        script: flutter pub get
#      - name: Build apk
#        script: flutter build apk --release --build-name=1.0.2 --build-number=6 --flavor development --dart-define=BASE_URL=https://api.unsplash.com/
      - name: Build aab
        script: flutter build aab --release --build-name=1.0.0 --build-number=1 --flavor production
#    publishing:
#      firebase:
#        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
#        android:
#          app_id: 1:220062871728:android:17d8024f4a5fc9e32b8b75
#          groups:
#            - phongpvs-team
#          artifact_type: 'apk'

