workflows:
  android-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    environment:
      flutter: 3.29.0
      groups:
        - firebase
    triggering:
      events:
        - push
        - pull_request
      branch_patterns: # Include or exclude watched branches
        - pattern: feature/codemagic
          include: true
          source: true
    artifacts:
      - build/**/outputs/bundle/developmentRelease/**/*.aab
      - build/**/outputs/apk/development/**/*.apk
    scripts:
      - name: Show firebase token
        script: echo $FIREBASE_TOKEN
      - name: Pub get
        script: flutter pub get
      - name: Build apk
        script: flutter build apk --release --flavor development
      - name: Build aab
        script: flutter build aab --release --flavor development
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        android:
          app_id: 1:220062871728:android:17d8024f4a5fc9e32b8b75
          groups:
            - PhongPV's Team
          artifact_type: 'apk'

