workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: 3.29.0
    scripts:
      - flutter pub get
      - echo "Hello World!"