workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    environment:
      flutter: 3.29.0
    triggering:
      events:
        - push
      branch_patterns: # Include or exclude watched branches
        - pattern: '*'
          include: true
          source: true
        - pattern: excluded-target
          include: false
          source: false
        - pattern: included-source
          include: true
          source: true
    scripts:
      - name: Pub get
        script: flutter pub get
      - name: Build aab
        script: flutter build aab --flavor development
